### ISSUE TITLE
能否实现变录音边识别呢？

### ISSUE THREAD

**Issue by baoxiangyang** [tencentyun/wafer2-aai-nodejs#2]
小程序文档支持mp3按帧获取数据，能否每次获取到一帧的数据的时候，上传到服务转换转换成pcm或wav格式的片段，再去调用ai的流式识别？
你这个我看也是录音完成后在分段流式识别。和录音完成后在识别完整语音也没有什么不同

**Comment by jas0ncn** [comment]
按帧转换成wav之后识别的准确度会有问题。这部分可以探讨一下，是否有更好的办法。您可以自己尝试修改一下，如果对准确性没有影响可以提交一个pr

**Comment by baoxiangyang** [comment]
好的 谢谢
